// Generated by CoffeeScript 1.9.3
define(function(require, exports, module) {
  var $, Backbone, doT, auth, appapi;
  $ = require('jquery');
  Backbone = require('backbone');
  doT = require('doT');
  auth = require('mod/auth');
  appapi = require('mod/api-config');
  require('gxdialog');


  exports = Backbone.View.extend({
    el: $('.IndexView'),
    events: {
      'click #home-login': 'logout'
    },
    initialize: function() {
      this.render();

      return this;
    },
    render: function() {
      var self;
      self = this;
      doT.static('/templates/home.html', function(html) {
        self.$el.html(html);
        self.$el.show();
        self.setHeaderInfo();
        self.fileSize();
      });
    },
    setHeaderInfo: function(){
      var user = auth.getUser();
      console.log(user);
      if(user && user.id){
        $('.yun-user').hide();
        $('.user-name').text(user.name || user.phone);
      }
    },
    logout: function(){
      $.gxDialog({
        title: '确认退出',
        width: 400,
        info: '确定退出云服务吗？',
        ok: function(){
          $.when($.ajax({
            url: appapi.account.logout
          })).then(function(){
            auth.setUser({});
            window.App.Views.go('login');
          }).fail(function(){
            auth.setUser({});
            window.App.Views.go('login');
          });
        },
        no: function(){
        }

      });

    },
    fileSize: function(){
      var fileSizeUrl = AppApi.files.fileSize;
      $.ajax({
        url: fileSizeUrl,
        type: 'POST',
        cache: false,
        dataType: window.DEBUG_TEST_DATA ? 'json':'jsonp',
        timeout: 8000,
        data: {},
        success: function(res) {
          if(res.code == 0 ){
            var userCount = 5,
                currCount = Math.round(res.data/1024/1024/1024),
                currCountMB = Math.round(res.data/1024/1024),
                proportion = "";
            var percentage = function(num, total) {
               return (Math.round(num / total * 10000) / 100.00 + "%");

            }
            proportion = percentage(currCount,userCount);
            $('#progress-num').animate({
              width: proportion},
            300, function() {});
            $('.currFileSize').text(currCountMB);

          }else if(res.code != 0){
            $.gxDialog({
              title: '',
              width: 400,
              timeout: 3000,
              info: res.msg
            });
          }
        },
        error: function(err) {
          console.log("error");
        }
      });
    }

  });
  return exports;
});

//# sourceMappingURL=index.js.map
