// Generated by CoffeeScript 1.9.3
define(function(require, exports, module) {
  var $, Backbone, doT;
  $ = require('jquery');
  Backbone = require('backbone');
  doT = require('doT'),
  auth = require('mod/auth'),
  appapi = require('mod/api-config');
  require('gxdialog');


  exports = Backbone.View.extend({
    el: $('.IndexView'),
    events: {
      'click #home-login': 'logout'
    },
    initialize: function() {
      this.render();

      return this;
    },
    render: function() {
      var self;
      self = this;
      doT.static('/templates/home.html', function(html) {
        self.$el.html(html);
        self.$el.show();
        self.setHeaderInfo();

      });
    },
    setHeaderInfo: function(){
      var user = auth.getUser();
      console.log(user);
      if(user && user.id){
        $('.yun-user').hide();
        $('.user-name').text(user.name);
      }
    },
    logout: function(){
      $.gxDialog({
        title: '确认退出',
        width: 400,
        info: '确定退出云服务吗？',
        ok: function(){
          $.when($.ajax({
            url: appapi.account.logout
          })).then(function(){
            auth.setUser({});
            window.App.Views.go('login');
          }).fail(function(){
            auth.setUser({});
            window.App.Views.go('login');
          });
        },
        no: function(){
        }

      });

    }
  });
  return exports;
});

//# sourceMappingURL=index.js.map
