// Generated by CoffeeScript 1.9.3

/*
  登陆
 */
define(function(require, exports, module) {
  var $, Backbone, appApi, auth, doT, validate;
  $ = require('jquery');
  Backbone = require('backbone');
  doT = require('doT');
  validate = require('jquery/jquery-validate');
  require('cookie');
  auth = require('mod/auth');
  appApi = require('mod/api-config');
  require('gxdialog');
  exports = Backbone.View.extend({
    el: $('.LoginView'),
    events: {
      'click #btn-login': 'login'
    },
    initialize: function() {
      this.render();
      return this;
    },
    render: function() {
      var self;
      self = this;
      doT["static"]('/templates/login.html', function(html) {
        self.$el.html(html);
        return self.bindEvent();
      });
      this.$el.show();
      return this;
    },
    bindEvent: function() {
      this.form = $('#defaultForm');
      this.form.validate({
        rules: {
          phone: {
            required: true
          },
          pwd: {
            required: true
          }
        },
        messages: {
          phone: {
            required: '请输入铂钰账号／手机号码'
          },
          pwd: {
            required: '请输入密码'
          }
        }
      });
      return null;
    },
    login: function() {
      var result, self;
      self = this;
      result = this.form.valid();
      if (result === true) {
        $('#btn-login').text('登陆中');
        return $.ajax({
          cache: false,
          url: appApi.login.login,
          data: $('#defaultForm').serialize(),
          success: function(result) {
            if (typeof result === 'string') {
              result = JSON.parse(result);
            }
            if (result.code === 0) {
              auth.setUser(result.data);
              window.App.Views.go('/');
            } else {
              $('#btn-login').text('重新登陆');
              $.gxDialog({
                width: '200',
                title: '提示',
                info: result.msg,
                okText: '确定',
                ok: function() {}
              });
            }
            return true;
          },
          error: function(err) {
            return $('.err-msg').show();
          }
        });
      }
    }
  });
  return exports;
});

//# sourceMappingURL=login.js.map
